###
POST http://localhost:8080/api/auth
Content-Type: application/x-www-form-urlencoded

login=cbalaminos@gmail.com&senha=cbalaminos@gmail.com

###
OPTIONS http://localhost:8080/api/auth
Content-Type: application/x-www-form-urlencoded
Origin: http://localhost:4200
Access-Control-Request-Method: POST

###
GET http://localhost:8090/quarkedu/boletim/267750/2417/emitir

###
GET http://localhost:8090/quarkedu/frequencia/267750/2417/emitir

###
GET http://localhost:8080/api/noticias/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU4NDYzNzY3Nywic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTg0NjM3Njc3ODg0LFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU4NzIyOTY3N30.MqVSh8N0gNA2ZecFwi0IZJlpNWVQL8y6XRFHxGBu36k

###
OPTIONS http://localhost:8080/api/noticias/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU4NDYzNzY3Nywic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTg0NjM3Njc3ODg0LFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU4NzIyOTY3N30.MqVSh8N0gNA2ZecFwi0IZJlpNWVQL8y6XRFHxGBu36k

###
GET http://localhost:8080/api/cobrancas/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/cobrancas/futuras/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/mensagens/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/mensagens/4/respostas/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/cobrancas/passadas/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/eventos/proximos-eventos/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/eventos/eventos-em-andamento/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/eventos/eventos-passados/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://localhost:8080/api/eventos/8/imagem

###
GET http://localhost:8080/api/eventos/50/imagem

###
GET http://localhost:8080/api/download/3fa354d1-7208-4a65-80e8-37c0bfd55e20/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxdWFya2VkdS1hZ2VuZGEtMCIsImlhdCI6MTU3NTU1MDE1Niwic3ViIjoie1wiaWRcIjowLFwiaWRVc3VhcmlvXCI6MCxcImRhdGFcIjoxNTc1NTUwMTU2NDQzLFwibG9naW5cIjpcImNiYWxhbWlub3NAZ21haWwuY29tXCIsXCJub21lXCI6bnVsbCxcImVtYWlsXCI6XCJjYmFsYW1pbm9zQGdtYWlsLmNvbVwiLFwiZ3J1cG9JZFwiOjAsXCJpbnN0aXR1aWNhb0lkXCI6MCxcInByb2R1dG9JZFwiOjAsXCJjb2RpZ29BcHBcIjpcInF1YXJrZWR1LWFnZW5kYVwiLFwiZnVuY2lvbmFsaWRhZGVzXCI6bnVsbCxcIm1ldGFEYWRvc1wiOntcImluc3RpdHVpY2FvRW5zaW5vSWRcIjozLFwicGVzc29hSWRcIjoxMTE0MSxcImFsdW5vc0lkXCI6WzI0MTcsMjQzM119fSIsImlzcyI6InF1YXJrZWR1LWFnZW5kYSIsImV4cCI6MTU3ODE0MjE1Nn0.0RHJFePBcK-SQjvKClrJzgaye01uoW3nGhisMa56K7A

###
GET http://testes-mpay.esig.com.br/api/api/pagamento/boleto/view/3cd69ec9102ab55de5daa533a8ad381f

###
POST https://testes-mpay.esig.com.br/api/api/pagamento/boleto/situacao/862e07784aaf26f198065a3ec7a4047b
AccessKey: 390628f06ba431ca772ceb94c00b7c45c200187738f7a577936c9ab7de4c4f29

###
GET http://testes-mpay.esig.com.br/api/api/status